### PR TITLE
Update ruby 2.2.2 rails 4.2.2

### PR DESCRIPTION
**Pull request by dan-palmer**
Ruby Version **2.2.0** -> **2.2.2**
Rails Version **4.2.0** -> **4.2.2**

### CODE REVIEW

**Comment by mattmb** [comment]
We're currently on 2.2.1 so will need to build a new package and container before we merge this.

**Comment by dan-palmer** [comment]
@mattmb oki doki :+1:

**Comment by dan-palmer** [comment]
@mattmb Spotted a potential bug with the rails mailers(/rails/mailers in development mode) which I think is related to the ruby upgrade.

**Comment by dan-palmer** [comment]
These are old versions. Canning this PR in favor of later stable versions.

**Pull request closed without merging**
