### PR TITLE
Admin panel PDF generation & PDF downloads.

### PR DESCRIPTION
**Pull request by dan-palmer**
Feature to stop such PM's & DM's hassling the devs.. :laughing:

### CODE REVIEW

**Comment by dan-palmer** [comment]
screen shot 2015-02-26 at 18 31 41

**Comment by tomwm** [comment]
this is cool. if this goes in do we want to think bout something better than basic auth or will that be enough for now? @mattmb @stevegraham @TrentDSD @helenmott

**Comment by mattmb** [comment]
Love how little code this took :+1: 

@dan-palmer how difficult would it be to separate the active admin stuff into a separate app so that we could run it in a different container to the main app?

**Comment by stevegraham** [comment]
That's the advantage of picking the right tools and producing well designed, reusable code. Something we've managed to do a good job of on this project.

+1 admin panel being another app. Only lives in the main app for expediency.

**Comment by dan-palmer** [comment]
@mattmb hmm perhaps we just submodule etfees repo and have an etfees-admin repo dedicated to this. Thoughts? @stevegraham @mattmb

**Pull request closed without merging**
