### PR TITLE
Move additional information rtf upload to claim details page

### PR DESCRIPTION
**Pull request by dan-palmer**
This renames the column on the claims table, because of this it will also mean we have to re-sync the files in S3. I just didn't want to have the uploader called additional_information_rtf & still have the additional_information_form.

Updated with new designs(Monday 9th March)

### CODE REVIEW

**Comment by dan-palmer** [comment]
@michaelelwin @tomwm

**Comment by dan-palmer** [comment]
@michaelelwin @tomwm 
claim details - gov uk

**Comment by dan-palmer** [comment]
### such copy changes
@michaelelwin @tomwm 
claim details - gov uk 1

**Comment by stevegraham** [comment]
what's the start for migrating the s3 filez?

**Comment by dan-palmer** [comment]
# claim details page
claim details - gov uk 2

# review page
![screen shot 2015-03-09 at 11 57 21]
(https://cloud.githubusercontent.com/assets/1006365/6554425/8bf6be64-c653-11e4-88ee-9f52755b484e.png)

@tomwm @michaelelwin

**Comment by tomwm** [comment]
Cool. I wonder if we should move the 'remove uploaded doc' underneath the
upload button. I think it would flow better in terms of hierarchy of
information.

Tom

On 9 March 2015 at 11:59, Dan Palmer <notifications@github.com> wrote:

> claim details page
>
> [image: claim details - gov uk 2]
> <https://cloud.githubusercontent.com/assets/1006365/6554426/8f2d3ee6-c653-11e4-8923-77302df832ac.png>
> review page
>
> [image: screen shot 2015-03-09 at 11 57 21]
> <https://cloud.githubusercontent.com/assets/1006365/6554425/8bf6be64-c653-11e4-88ee-9f52755b484e.png>
>
> @tomwm <https://github.com/tomwm> @michaelelwin
> <https://github.com/michaelelwin>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/pull/623#issuecomment-77841025>
> .
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>

**Comment by stevegraham** [comment]
kewl

**Pull request merged**
