### PR TITLE
Static error pages

### PR DESCRIPTION
**Pull request by stevegraham**
Error pages for 404, 422, 500, and 503 HTTP errors

URLs:
http://0.0.0.0:3000/404.html
http://0.0.0.0:3000/422.html
http://0.0.0.0:3000/500.html
http://0.0.0.0:3000/503.html

@Demwunz There is an issue with the footer not being on the bottom of the page. Can you take a look? Also maybe we can remove the references to the JS too for these pages?

### CODE REVIEW

**Comment by tomwm** [comment]
@stevegraham obviosuly i cant see the loal urls. Can i check you used the copy on here for the 500's
https://docs.google.com/a/digital.justice.gov.uk/document/d/1aN0dT1lPZFCdID_7DRCe5LCFwNpq3rOvX6mYPPo3DVM/edit for

**Comment by stevegraham** [comment]
I didn't use that copy but @Demwunz can change it when he's going over it.

**Comment by tomwm** [comment]
cool, make it so @Demwunz

**Comment by Demwunz** [comment]
!(make it so)[http://amazingr.com/make-it-so.gif]

**Comment by tomwm** [comment]
http://media3.giphy.com/media/MMpZTGSJn2eHu/200.gif

**Comment by Demwunz** [comment]
@tomwm I've added a link on one page, but it all depends on how long the parallel service will be running for. Moreover, if they start an application in the other service and return, they will have committed to a system that will ultimately be phased out. 

There is also a danger that any 5xx 4xx error could just be a temporary glitch, by making them wait a few minutes or reloading would be a more suitable path of action.

**Comment by stevegraham** [comment]
Thanks @Demwunz

**Pull request merged**
