### PR TITLE
Fixes/gh issue 518 Maintenance page

### PR DESCRIPTION
**Pull request by cleargif**
- Copy and tests updated for service down page.

route: /maintenance

Not too sure about the naming - but does it matter? Will gladly update if required.

@mattmb @dan-palmer @Demwunz

### CODE REVIEW

**Comment by mattmb** [comment]
@cleargif that looks good to me :-)

**Comment by stevegraham** [comment]
:-1:

**Comment by tomwm** [comment]
smiley faces and thumbs down. Hmmm. @TrentDSD thoughts?

**Comment by stevegraham** [comment]
At *most* this feature is a static page, i.e. 503.html in /public. There is no need for a controller or markdown. A controller has no advantages and introduces code that @dan-palmer or myself to maintain.

Honestly this has no business being in the app itself whatsoever. It should be something in an S3 bucket shared amongst all services.

**Comment by cleargif** [comment]
Closing. Feature will be added in a new PR.

**Pull request closed without merging**
