### PR TITLE
Render errors on base

### PR DESCRIPTION
**Pull request by stevegraham**
At this point we only use this on the user sessions page. The behaviour
is if there are errors on base show the errors in the notification
header, else show the fix errors below message.

### CODE REVIEW

**Comment by stevegraham** [comment]
Looks like this
lel

**Comment by Demwunz** [comment]
@stevegraham check last commit, removed excess whitespace.

**Comment by stevegraham** [comment]
@demwunz thank you sir

**Comment by Demwunz** [comment]
@stevegraham  no problemo

**Pull request merged**
