### PR TITLE
Plain text emails

### PR DESCRIPTION
**Pull request by stevegraham**
- [x] fix broken tests
- [x] fix up deprecation warnings

Emails:

access_details_email

```
Claim number: X7V2-PMCC

You’ve started a claim to an employment tribunal. To return to your claim you’ll
need your claim number (above), and memorable word.

Clicking on the links below will not work. Please copy and paste URLs into your
browser.

Complete claim: http://localhost:3000/apply/session/new

You’ll receive a confirmation email once you’ve submitted your claim.

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply or click any links
  - forward it to security@digital.justice.gov.uk
```

group_payment_with_remission

```
Claim number: T96M-M6XF

Barrington Wrigglesworth

Thank you for submitting your claim to an employment tribunal.

What happens next:
  - You have said you want to apply for fee remission. You must apply within 7 days, or your claim may be rejected.
    Apply for fee remission: https://www.employmenttribunals.service.gov.uk/remissions
  - We’ll review your claim for remission and contact you to explain the next steps.

Submission details:
Claim completed: See attached PDF
Claim submitted: Submitted 20 January 2015
Additional documents: file.rtf
Issue fee paid: £250.00

Your feedback helps us improve this service:
 https://www.surveymonkey.com/s/FH3QFS8

Help us keep track. Please complete our diversity monitoring questionnaire.
 https://www.employmenttribunals.service.gov.uk/forms/form/175/en/diversity_monitoring_questionnaire

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply to it or click any links
  - forward it to security@digital.justice.gov.uk
```

group_payment_with_remission_payment_failed

```
Claim number: SCJ3-6HSX

Barrington Wrigglesworth

Your claim to an employment tribunal has been submitted but unfortunately we weren’t able to process your payment.

What happens next:
  - We’ll contact you within 5 working days to arrange payment.
  - You have said you want to apply for fee remission. You must apply within 7 days, or your claim may be rejected.
    Apply for fee remission: https://www.employmenttribunals.service.gov.uk/remissions
  - We’ll review your claim for remission and contact you to explain the next steps.

Submission details:
Claim completed: See attached PDF
Claim submitted: Submitted 20 January 2015
Additional documents: file.rtf
Issue fee paid: Unable to process payment

Your feedback helps us improve this service:
 https://www.surveymonkey.com/s/FH3QFS8

Help us keep track. Please complete our diversity monitoring questionnaire.
 https://www.employmenttribunals.service.gov.uk/forms/form/175/en/diversity_monitoring_questionnaire

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply to it or click any links
  - forward it to security@digital.justice.gov.uk
```

payment_no_remission

```
Claim number: 9C3C-N0XR

Barrington Wrigglesworth

Thank you for submitting your claim to an employment tribunal.

What happens next:
  - You have said you want to apply for fee remission. You must apply within 7 days, or your claim may be rejected.
  - We’ll contact you when your claim has been sent to the respondent and explain the next steps.

Submission details:
Claim completed: See attached PDF
Claim submitted: Submitted 20 January 2015 to tribunal office Birmingham, Centre City Tower, 5­7 Hill Street, Birmingham B5 4UU
Additional documents: file.rtf<br />file.csv
Issue fee paid: £250.00

Your feedback helps us improve this service:
 https://www.surveymonkey.com/s/FH3QFS8

Help us keep track. Please complete our diversity monitoring questionnaire.
 https://www.employmenttribunals.service.gov.uk/forms/form/175/en/diversity_monitoring_questionnaire

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply to it or click any links
  - forward it to security@digital.justice.gov.uk
```

payment_no_remission_payment_failed

```
Claim number: R17K-0B63

Barrington Wrigglesworth

Your claim to an employment tribunal has been submitted but unfortunately we weren’t able to process your payment.

What happens next:
  - We’ll contact you within 5 working days to arrange payment.
  - You have said you want to apply for fee remission. You must apply within 7 days, or your claim may be rejected.
  - We’ll contact you when your claim has been sent to the respondent and explain the next steps.

Submission details:
Claim completed: See attached PDF
Claim submitted: Submitted 20 January 2015 to tribunal office Birmingham, Centre City Tower, 5­7 Hill Street, Birmingham B5 4UU
Additional documents: file.rtf<br />file.csv
Issue fee paid: Unable to process payment

Your feedback helps us improve this service:
 https://www.surveymonkey.com/s/FH3QFS8

Help us keep track. Please complete our diversity monitoring questionnaire.
 https://www.employmenttribunals.service.gov.uk/forms/form/175/en/diversity_monitoring_questionnaire

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply to it or click any links
  - forward it to security@digital.justice.gov.uk
```

remission_only

```
Claim number: 4BKK-2CSZ

Barrington Wrigglesworth

Thank you for submitting your claim to an employment tribunal.

What happens next:
  - You have said you want to apply for fee remission. You must apply within 7 days, or your claim may be rejected.
    Apply for fee remission: https://www.employmenttribunals.service.gov.uk/remissions
  - We’ll review your claim for remission and contact you to explain the next steps.

Submission details:
Claim completed: See attached PDF
Claim submitted: Submitted 20 January 2015
Additional documents: file.rtf<br />file.csv

Your feedback helps us improve this service:
 https://www.surveymonkey.com/s/FH3QFS8

Help us keep track. Please complete our diversity monitoring questionnaire.
 https://www.employmenttribunals.service.gov.uk/forms/form/175/en/diversity_monitoring_questionnaire

Contact us: http://www.justice.gov.uk/contacts/hmcts/tribunals/employment

If you’re not sure whether an email is from the Ministry of Justice then:
  - do not reply to it or click any links
  - forward it to security@digital.justice.gov.uk
```

### CODE REVIEW

**Comment by dan-palmer** [comment]
Because I have mad OCD I wrote a method to wrap the mail return value in the previews that removes the attachments and reassembles the correct parts so the content can be viewed for text or html.

```ruby
class  ConfirmationEmailPreview < ActionMailer::Preview
 
 ....
 
 private

  def claim_for(trait)
    claim = FactoryGirl.create(:claim, :with_pdf, trait)
    mail = BaseMailer.confirmation_email(claim)
    multipart_preview_fix(mail)
  end

  def multipart_preview_fix(mail)
    mail.tap do |m|
      true_mail_parts = m.parts.select(&:multipart?).first.body.parts
      m.without_attachments!
      { 'text_part=' => /text\/plain/, 'html_part=' => /text\/html/ }.each do |mutator, content_match|
        m.send(mutator, true_mail_parts.select { |p| p.content_type =~ content_match }.first)
      end
      # text part adds two parts, the head contains junk, lets show it the door!
      m.parts.shift
    end
  end
end
```

**Comment by stevegraham** [comment]
@michaelelwin @tomwm do the above emails look ok?

**Comment by stevegraham** [comment]
```Additional documents: file.rtf<br />file.csv```

```<br />``` is a HTML tag is it ok if we do this ```Additional documents: file.rtf, file.csv``` in both HTML and plain text emails?

**Comment by michaelelwin** [comment]
@stevegraham @tomwm have given the plain text emails a check - quite  a few changes needed. See comments and text changes in BLUE in google doc below  

https://docs.google.com/a/digital.justice.gov.uk/document/d/1HOB0tXbrkJVPBxUk12oNRRLnfcQrRbpuSsBOMpAPfBs/edit?userstoinvite=stevie.graham@digital.justice.gov.uk

**Comment by stevegraham** [comment]
@michaelelwin Cheers eagle eyes :bird:. Fixed everything apart from numeric lists it's too fiddly at this point. Happy to revisit in the future if it is sufficiently problematic for users.

**Pull request merged**
