### PR TITLE
added page number into page title

### PR DESCRIPTION
**Pull request by Demwunz**

### CODE REVIEW

**Comment by dan-palmer** [comment]
@Demwunz is this ready to go?

**Comment by Demwunz** [comment]
@dan-palmer yes it is :)

**Comment by Demwunz** [comment]
don't merge just yet please @dan-palmer I want to double check mobile layout. thanks :)

**Comment by Demwunz** [comment]
good to go @dan-palmer

**Comment by dan-palmer** [comment]
:+1:

**Pull request merged**
