### PR TITLE
Payment page layout and copy amends.

### PR DESCRIPTION
**Pull request by dan-palmer**
### Sir Lord Elwins Content:
screen shot 2015-02-05 at 17 47 01
### Before:
screen shot 2015-02-05 at 18 05 58
### After:
screen shot 2015-02-05 at 18 04 17

- [x] Adds callout with fee
- [x] Adds cheque information
- [x] Include a link to the PDF
- [x] ordered list should use numbers @Demwunz 

** pdf link will be handled in a separate PR

### CODE REVIEW

**Comment by tomwm** [comment]
Nice one Dan. Michael, there needs to be just a few copy tweaks based on
something that Dan T let us know today. They can be done when @demunz
sprinkles it.

1. before each address we need to write something akin to "If your work
address is in England or wales:" and  "If your work address is in
Scotland:".

2. We can't use court finder sadly.(I can explain to anyone that wants to
know why). So we are going to have to put some extra text at the end of
that line that says something akin to "if you don't know where you local
tribunal office is contact us [link]"




On 5 February 2015 at 18:09, Dan Palmer <notifications@github.com> wrote:

> Sir Lord Elwins Content:
> [image: screen shot 2015-02-05 at 17 47 01]
> <https://cloud.githubusercontent.com/assets/1006365/6066008/8b68d0c8-ad61-11e4-90aa-cd6f2751d7c2.png>
> Before:
> [image: screen shot 2015-02-05 at 18 05 58]
> <https://cloud.githubusercontent.com/assets/1006365/6066024/ad262e4a-ad61-11e4-9198-4ed16ad42952.png>
> After:
> [image: screen shot 2015-02-05 at 18 04 17]
> <https://cloud.githubusercontent.com/assets/1006365/6066010/90251522-ad61-11e4-854c-a35d2d2865f1.png>
>
>    -  Adds callout with fee
>    -  Adds cheque information
>    -  Spacing issues @Demwunz <https://github.com/Demwunz>
>    -
>       should use numbers @Demwunz <https://github.com/Demwunz>
>     -  Court finder link @tomwm <https://github.com/tomwm> ** pdf link
>    will be handled in a separate PR
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ministryofjustice/atet/pull/617
> Commit Summary
>
>    - Payment page layout and copy amends.
>
> File Changes
>
>    - *M* app/views/payments/show.html.slim
>    <https://github.com/ministryofjustice/atet/pull/617/files#diff-0> (23)
>    - *M* config/locales/en.yml
>    <https://github.com/ministryofjustice/atet/pull/617/files#diff-1> (27)
>    - *M* spec/features/payments_spec.rb
>    <https://github.com/ministryofjustice/atet/pull/617/files#diff-2> (8)
>
> Patch Links:
>
>    - https://github.com/ministryofjustice/atet/pull/617.patch
>    - https://github.com/ministryofjustice/atet/pull/617.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/pull/617>.
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>

**Comment by dan-palmer** [comment]
@tomwm @michaelelwin 

#### Revision 5069

screen shot 2015-02-06 at 12 21 09

**Comment by michaelelwin** [comment]
A job well done, Squire Palmer. Just a couple of things -

- Bullet points should be numbers
- Step 3 copy is not what's in doc.

cheers

Michael Elwin
Digital Content Designer
07947 557671

**Comment by stevegraham** [comment]
Thanks

**Comment by stevegraham** [comment]
LGTM

**Comment by dan-palmer** [comment]
cheers @matharden for such lists. you have one coin credit in your account.

**Pull request merged**
