### PR TITLE
Change from Beta to Live & updated FE gems

### PR DESCRIPTION
**Pull request by dan-palmer**

### CODE REVIEW

**Comment by dan-palmer** [comment]
@Demwunz The static pages have some references to the app being in beta still.

**Comment by dan-palmer** [comment]
e.g https://github.com/ministryofjustice/atet/blob/issues/664/public/404.html#L102

**Comment by tomwm** [comment]
@demwunz can you address @dan-palmer comment above? We are hopefully switching off Jadu this week and will then need to remove all beta banners.

**Comment by Demwunz** [comment]
@dan-palmer removed static references :8ball:

**Comment by dan-palmer** [comment]
@Demwunz thank you sir.. i'll have a glance over

**Pull request merged**
